deploy profile on icpumpfun domain
go-bazzinga/hot-or-not-web-leptos-ssr pull request #404
Opened 2024-09-12 18:21 UTC by ravibazz

## Changes
- add ab selector for icpump.fun domain

2024-09-12 18:59 UTC, rupansh requested changes

2024-09-12 18:59 UTC, rupansh commented on ssr/src/page/root.rs
> +    let host_str = create_resource(|| {}, |_| async { get_host_async().await });
do we really need get_host_async?

2024-09-13 04:46 UTC, ravibazz commented on ssr/src/page/root.rs
> +    let host_str = create_resource(|| {}, |_| async { get_host_async().await });
Yes, tried get_host that's not working

2024-09-14 10:20 UTC, rupansh-gob approved these changes

2024-09-14 10:20 UTC, merged