Feat/share token
go-bazzinga/hot-or-not-web-leptos-ssr pull request #440
Opened 2024-09-18 15:27 UTC by prakash-bhatt-rs

2024-09-18 17:34 UTC, prakash-bhatt-rs commented
#416

2024-09-18 17:37 UTC, ravibazz requested changes

2024-09-18 17:37 UTC, ravibazz commented on ssr/src/page/token/info.rs
> +                            // </div>
Should we remove the commented code?

2024-09-18 17:37 UTC, ravibazz commented on ssr/src/page/wallet/tokens.rs
> +                                // </div>
Lets remove the commented code

2024-09-18 17:51 UTC, prakash-bhatt-rs commented on ssr/src/page/wallet/tokens.rs
> +                                // </div>
Okay.

2024-09-19 12:12 UTC, ravibazz requested changes
Changes looks good just need to move some of the components to components folder as they can be reused in future in other pages.

2024-09-19 12:12 UTC, ravibazz commented on ssr/src/page/wallet/share_token_popup.rs
> +}
Some of the components in this file looks reusable. Should be moved inside components folder?

2024-09-19 12:40 UTC, ravibazz commented on ssr/src/component/share_popup.rs
> +}
Why is this needed?

2024-09-19 13:21 UTC, ravibazz approved these changes

2024-09-19 13:59 UTC, merged