Fix: Token List click on share button takes user to next screen
go-bazzinga/hot-or-not-web-leptos-ssr pull request #448
Opened 2024-09-19 15:48 UTC by prakash-bhatt-rs

2024-09-20 11:00 UTC, prakash-bhatt-rs commented
- I have extracted the TokenTile as a separate component, 
- Fixed click error (In wallet screen upon clicking the Token share button, page was navigating automatically to token info screen ).
- Used TokenTile component into Token at profile.
- Added airdrop-amt as query param for Token share url.

2024-09-20 11:32 UTC, harshitasrivastav28 commented
When I click on the link shared to other users, the app throws my Coffee break error. @prakash-bhatt-rs

2024-09-20 11:42 UTC, prakash-bhatt-rs commented
web::share_url() API is already appending the base url on share. This was causing error like base appearing twice on the shared url. 
e.g. 
https://yral.com/yral.com/profile/j2zob-vt6qd-fgoz2-q2hxj-huvmo-nl7jl-rzcm7-ikvds-hhkfj-rllw3-lqe?tab=tokens

2024-09-20 11:56 UTC, harshitasrivastav28 commented
The issue has been resolved and working as expected. @prakash-bhatt-rs This is good to go! Please assign it to reviewer

2024-09-20 15:47 UTC, rupansh-gob requested changes
minor changes

2024-09-20 15:47 UTC, rupansh-gob commented on ssr/src/page/profile/tokens.rs
> +// #[component]
Nuke the unused component instead of commenting it

2024-09-20 15:47 UTC, rupansh-gob commented on ssr/src/component/share_popup.rs
> +    style: Option<String>,
use 
```rust
#[prop(optional)] style: String
```

2024-09-21 06:46 UTC, rupansh-gob approved these changes

2024-09-21 07:45 UTC, merged